### ISSUE TITLE
Teksture

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG133-pathsolver#1]
Neophodno je dodati teksture u projekat.

**Comment by giomla** [comment]
Da li je dovoljno da npr dodam pozadinsku teksturu neba ( npr oblake ili zvezde) ili npr da kvadratima dodam neke teksture , tj da li je dovoljna jedno koriscenje tekture? @rastko-djordjevic-edu

**Comment by giomla** [comment]
Dodate su teksture u projekat.
