### ISSUE TITLE
Refaktorisanje koda

### ISSUE THREAD

**Issue by rastko-djordjevic-edu** [MATF-RG19/RG133-pathsolver#5]
Refaktorisati kod, main.c na vise fajlova po potrebi. 

Trenutno u kodu ima dosta copy-paste-a uz male izmene, npr prilikom obrade razlicitih nivoa. Ovo je super znak da taj kod treba staviti u funkciju. Prakticno kod svakog switch-a je radjena ista stvar 10 puta i svuda je iskopiran kod, ovo dosta otezava naknadne izmene.

**Comment by giomla** [comment]
Refaktorisao sam kod, uklonio sam silne switch naredbe, sem jedne,  dodao sam pomocne funkcije, 
podelio sam main.c na funkcije.c funkcije.h koji sadrzi globalne promenljive koje koriste nivoi , pored pomenutih funkcija. U dva commita , u prvom sam podelio fajl i dodao funkcije u drugom sam reorganizovao kod kako ne bi bilo toliko copy paste.
To bi bili commitovi od 09.06.2020.
